spring:
  application:
    name: actuator-sample-application

management:
  endpoints:
    web:
      exposure:
        include:
         - health
         - prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}